import Head from "next/head";
import styles from "../styles/Home.module.css";
import Data from "../test_solution/data.json";
import { flatObjToMap } from "../test_solution/flatObjToMap";

export default function Home() {
  // Function takes one parameter, the JSON file named Data
  const handleClick = (obj) => {
    flatObjToMap(obj);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pluria Dev Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p
          style={{
            cursor: "pointer",
            color: "white",

            fontSize: "3rem",
          }}
          onClick={() => handleClick(Data)}
        >
          click here
        </p>
        <p style={{ fontSize: "0.7rem", color: "white" }}>
          (then check the console log)
        </p>
      </main>
    </div>
  );
}
